import Head from "next/head";

export default function Home() {
  return (
    <div className='px-8 mt-10'>
      <Head>
        <title>Article Preview Component</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='mx-auto lg:w-3/5 lg:flex lg:flex-row lg:h-auto'>
        <img
          src='/image/drawers.jpg'
          alt='drawers'
          className='rounded-tr-md rounded-tl-md h-48 w-full lg:h-auto lg:w-2/5 lg:rounded-bl-md lg:rounded-tr-none'
        />
        <div className='bg-white p-8 rounded-bl-md rounded-br-md lg:rounded-bl-none lg:rounded-tr-m'>
          <h2 className='text-gray-700 font-semibold'>
            Shift overall look and fell by adding these wonderfull touches to
            furniture in your home.
          </h2>
          <p className='text-sm text-gray-600 mt-4'>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec
            scelerisque faucibus orci quis dignissim. Vestibulum mollis auctor
            dui, eget sodales risus maximus quis. Sed at vulputate dui, sed
            mollis lorem. Nullam egestas tristique consectetur. Phasellus non
            scelerisque felis, nec semper enim
          </p>
          <div className='flex items-center mt-8'>
            <div className='flex items-center'>
              <img
                src='/image/avatar-michelle.jpg'
                alt='avatar'
                className='h-10 w-10 rounded-full'
              />
              <div className='ml-4'>
                <p className='text-gray-800 text-sm font-semibold'>
                  Michelle Appleton
                </p>
                <p className='text-gray-600 text-sm'>30 August 2021</p>
              </div>
            </div>
            <div className='w-8 h-8 rounded-full ml-auto bg-gray-200 flex items-center justify-center pb-1'>
              <svg xmlns='http://www.w3.org/2000/svg' width='15' height='13'>
                <path
                  fill='#6E8098'
                  d='M15 6.495L8.766.014V3.88H7.441C3.33 3.88 0 7.039 0 10.936v2.049l.589-.612C2.59 10.294 5.422 9.11 8.39 9.11h.375v3.867L15 6.495z'
                />
              </svg>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
